"use client";

import { useState } from "react";
import { PlusIcon } from "@heroicons/react/24/outline";

export function ModuleListPage({ eyebrow, title, description, action, items }: { eyebrow: string; title: string; description: string; action: string; items: readonly [string, string, string][] }) {
  const [notice, setNotice] = useState("");
  return <main className="mx-auto max-w-7xl space-y-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-wider text-brand-600">{eyebrow}</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight text-slate-950">{title}</h1><p className="mt-1 text-sm text-slate-500">{description}</p></div><button type="button" onClick={() => setNotice(`${action} opened. Connect this workflow to the ITAM API to persist changes.`)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-brand-700"><PlusIcon className="h-4 w-4" /> {action}</button></header>{notice && <div role="status" className="flex items-center justify-between rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800"><span>{notice}</span><button type="button" onClick={() => setNotice("")} aria-label="Dismiss notification">×</button></div>}<section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-base font-extrabold">Current records</h2></div><div className="overflow-x-auto"><table className="min-w-[620px] w-full text-left"><thead className="bg-blue-50/70 text-[11px] font-bold text-slate-600"><tr><th className="px-5 py-3">Name</th><th className="px-5 py-3">Details</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map(([name, details, status]) => <tr key={name} className="text-sm hover:bg-slate-50"><td className="px-5 py-3 font-semibold text-slate-800">{name}</td><td className="px-5 py-3 text-slate-600">{details}</td><td className="px-5 py-3"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-brand-700">{status}</span></td></tr>)}</tbody></table></div></section></main>;
}
