"use client";

import { useState } from "react";

type ToggleSetter = (value: boolean | ((previous: boolean) => boolean)) => void;

const roles = [
  ["Super Admin", "Full platform access, organization subscription, and company provisioning.", "2 users"],
  ["IT Admin", "Organization settings, users, roles, and all ITAM modules.", "5 users"],
  ["Hardware Admin", "Hardware inventory, assignment, lifecycle, and maintenance.", "12 users"],
  ["Reporting User", "Read-only access to reporting and approved exports.", "38 users"],
] as const;

const integrations = [
  ["Microsoft Entra ID", "Directory sync", "Connected", "2,186 users synced"],
  ["Okta", "Single sign-on", "Connected", "SAML 2.0 enabled"],
  ["ServiceNow", "Service desk", "Not connected", "Link incidents and assets"],
  ["Jira Service Management", "Service desk", "Not connected", "Link requests and assets"],
] as const;

export default function SettingsPage() {
  const [saved, setSaved] = useState(false);
  const [auditLog, setAuditLog] = useState(true);
  const [mfa, setMfa] = useState(true);
  return <main className="mx-auto max-w-7xl space-y-8">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-brand-600">IT administration</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Organization settings</h1><p className="mt-2 text-slate-500">Configure company details, access control, security, and integrations.</p></div><button onClick={() => setSaved(true)} className="rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-700">Save changes</button></header>
    {saved && <div role="status" className="flex items-center justify-between rounded-xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm text-emerald-900"><span>Settings saved locally. Connect these controls to your configuration API to persist them.</span><button onClick={() => setSaved(false)} className="ml-4 font-semibold">Dismiss</button></div>}
    <section className="grid gap-6 lg:grid-cols-[1.15fr_1fr]"><article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-6"><h2 className="font-semibold text-slate-900">Organization profile</h2><p className="mt-1 text-sm text-slate-500">Details shown across your Bold And Wise ITAM workspace.</p></div><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Organization name<input defaultValue="Acme Technologies India" className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100" /></label><label className="text-sm font-medium text-slate-700">Primary domain<input defaultValue="acme.example" className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100" /></label><label className="text-sm font-medium text-slate-700">Default timezone<select defaultValue="Asia/Kolkata" className="mt-2 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-brand-500"><option value="Asia/Kolkata">India Standard Time</option><option value="Europe/London">Greenwich Mean Time</option><option value="America/New_York">Eastern Time</option></select></label><label className="text-sm font-medium text-slate-700">Asset tag prefix<input defaultValue="AST" className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100" /></label></div></article><article className="rounded-xl bg-slate-950 p-6 text-white shadow-sm"><p className="text-sm font-medium text-slate-400">Workspace plan</p><h2 className="mt-2 text-2xl font-bold">Enterprise</h2><p className="mt-2 text-sm leading-6 text-slate-400">Your subscription supports up to 100,000 managed endpoints and advanced discovery.</p><div className="mt-8 space-y-4 border-t border-white/10 pt-5 text-sm"><div className="flex justify-between"><span className="text-slate-400">Managed endpoints</span><span className="font-semibold">12,486 / 100,000</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[12.5%] rounded-full bg-brand-500" /></div><button className="pt-2 font-semibold text-brand-400 hover:text-brand-300">Manage subscription →</button></div></article></section>
    <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="font-semibold text-slate-900">Roles & access</h2><p className="mt-1 text-sm text-slate-500">Assign least-privilege access to your ITAM workspace.</p></div><button className="text-sm font-semibold text-brand-600 hover:text-brand-700">Manage users →</button></div><div className="divide-y divide-slate-100">{roles.map(([title, description, users]) => <div key={title} className="flex flex-col gap-2 px-6 py-4 sm:flex-row sm:items-center sm:gap-5"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-brand-50 text-sm font-bold text-brand-600">{title.charAt(0)}</div><div className="flex-1"><p className="font-semibold text-slate-800">{title}</p><p className="mt-0.5 text-sm text-slate-500">{description}</p></div><span className="text-sm font-medium text-slate-600">{users}</span><button className="text-left text-sm font-semibold text-brand-600 hover:text-brand-700">Edit</button></div>)}</div></section>
    <section className="grid gap-6 lg:grid-cols-2"><article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div><h2 className="font-semibold text-slate-900">Security & audit</h2><p className="mt-1 text-sm text-slate-500">Protect account access and record critical events.</p></div><div className="mt-6 divide-y divide-slate-100 border-y border-slate-100">{[["Require multi-factor authentication", "All administrators must verify with a second factor.", mfa, setMfa], ["Immutable audit logging", "Track asset, license, role, and configuration changes.", auditLog, setAuditLog]].map(([title, description, enabled, setter]) => <div key={title as string} className="flex items-center gap-4 py-4"><div className="flex-1"><p className="text-sm font-semibold text-slate-800">{title as string}</p><p className="mt-1 text-sm leading-5 text-slate-500">{description as string}</p></div><button aria-pressed={enabled as boolean} onClick={() => (setter as ToggleSetter)(!(enabled as boolean))} className={`relative h-6 w-11 rounded-full transition ${(enabled as boolean) ? "bg-brand-600" : "bg-slate-200"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${(enabled as boolean) ? "left-6" : "left-1"}`} /></button></div>)}</div><button className="mt-5 text-sm font-semibold text-brand-600 hover:text-brand-700">View audit logs →</button></article><article className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-5"><h2 className="font-semibold text-slate-900">Integrations</h2><p className="mt-1 text-sm text-slate-500">Connect directory, identity, and service-desk tools.</p></div><div className="divide-y divide-slate-100">{integrations.map(([name, type, state, detail]) => <div key={name} className="flex items-center gap-4 px-6 py-4"><span className="grid h-9 w-9 place-items-center rounded-lg bg-slate-100 text-slate-600">⌘</span><div className="min-w-0 flex-1"><p className="font-semibold text-slate-800">{name}</p><p className="text-sm text-slate-500">{type} · {detail}</p></div><span className={`hidden text-xs font-semibold sm:inline ${state === "Connected" ? "text-emerald-600" : "text-slate-400"}`}>{state}</span><button className="text-sm font-semibold text-brand-600 hover:text-brand-700">{state === "Connected" ? "Manage" : "Connect"}</button></div>)}</div></article></section>
  </main>;
}
