import Link from "next/link";

export default async function AssetDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  return <main className="mx-auto max-w-7xl space-y-8">
    <Link href="/assets" className="inline-flex text-sm font-semibold text-brand-600 hover:text-brand-700">← Back to assets</Link>
    <header className="flex flex-col justify-between gap-4 rounded-xl border border-slate-200 bg-white p-6 shadow-sm lg:flex-row lg:items-start"><div className="flex gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-xl bg-brand-50 text-xl font-bold text-brand-700">MB</span><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-bold tracking-tight text-slate-950">MacBook Pro 14&quot;</h1><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">Assigned</span></div><p className="mt-2 text-sm text-slate-500">Asset tag: <span className="font-semibold text-slate-700">{id}</span> · Apple M3 Pro · 18 GB unified memory</p></div></div><div className="flex gap-3"><button className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Edit asset</button><button className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white hover:bg-brand-700">Assign / transfer</button></div></header>
    <section className="grid gap-6 lg:grid-cols-[1.5fr_1fr]"><article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold text-slate-900">Asset details</h2><dl className="mt-6 grid gap-x-8 gap-y-5 sm:grid-cols-2">{[["Category", "Laptop"], ["Manufacturer", "Apple"], ["Serial number", "C02ZD1ABC123"], ["Purchase date", "08 May 2026"], ["Purchase cost", "₹2,49,900"], ["Warranty expires", "08 May 2029"], ["Location", "Mumbai · HQ"], ["Cost center", "Engineering · 4102"]].map(([label, value]) => <div key={label}><dt className="text-sm text-slate-500">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-800">{value}</dd></div>)}</dl></article><article className="rounded-xl bg-slate-950 p-6 text-white shadow-sm"><p className="text-sm font-medium text-slate-400">Current assignment</p><div className="mt-5 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-brand-600 text-sm font-bold">PS</span><div><p className="font-semibold">Priya Sharma</p><p className="text-sm text-slate-400">Product Design · Mumbai HQ</p></div></div><div className="mt-8 border-t border-white/10 pt-4"><p className="text-sm text-slate-400">Assigned since</p><p className="mt-1 font-semibold">12 May 2026</p><button className="mt-5 text-sm font-semibold text-brand-400 hover:text-brand-300">View assignment history →</button></div></article></section>
    <section className="grid gap-6 lg:grid-cols-[1.5fr_1fr]"><article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold text-slate-900">Lifecycle history</h2><div className="mt-6 space-y-6 border-l border-slate-200 pl-5">{[["12 May 2026", "Assigned to Priya Sharma", "Asset was deployed from Mumbai HQ inventory."], ["09 May 2026", "Inventory received", "Purchase order PO-2026-184 received and asset tagged."], ["08 May 2026", "Procured from Apple India", "Added to the FY 2026 fleet refresh order."]].map(([date, title, note]) => <div key={date} className="relative"><span className="absolute -left-[1.65rem] top-1.5 h-3 w-3 rounded-full border-2 border-white bg-brand-500" /><p className="text-xs font-semibold text-slate-400">{date}</p><p className="mt-1 font-semibold text-slate-800">{title}</p><p className="mt-1 text-sm text-slate-500">{note}</p></div>)}</div></article><article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold text-slate-900">Device health</h2><div className="mt-6 space-y-5">{[["Last seen", "Today, 10:31", "text-emerald-600"], ["Encryption", "FileVault enabled", "text-emerald-600"], ["OS patch level", "Current", "text-emerald-600"], ["Security agent", "Healthy", "text-emerald-600"]].map(([label, value, color]) => <div key={label} className="flex items-center justify-between"><span className="text-sm text-slate-500">{label}</span><span className={`text-sm font-semibold ${color}`}>{value}</span></div>)}</div><button className="mt-7 text-sm font-semibold text-brand-600 hover:text-brand-700">View telemetry →</button></article></section>
  </main>;
}
