"use client";

import Link from "next/link";
import { CubeIcon, CheckCircleIcon, WrenchScrewdriverIcon, ShieldCheckIcon, ClipboardDocumentCheckIcon, ComputerDesktopIcon, DevicePhoneMobileIcon, PrinterIcon } from "@heroicons/react/24/outline";
import { useMemo, useState } from "react";
import { useWorkspaceData } from "@/components/providers/workspace-data-provider";

const categoryIcon = { Laptop: ComputerDesktopIcon, Desktop: ComputerDesktopIcon, Mobile: DevicePhoneMobileIcon, Printer: PrinterIcon, Monitor: ComputerDesktopIcon } as const;
const statusStyle = { "In use": "bg-emerald-50 text-emerald-700", "In stock": "bg-blue-50 text-blue-700", "In repair": "bg-amber-50 text-amber-700" } as const;

export default function DashboardPage() {
  const [query, setQuery] = useState("");
  const { assets } = useWorkspaceData();
  const visibleAssets = useMemo(() => assets.filter((asset) => Object.values(asset).join(" ").toLowerCase().includes(query.toLowerCase())), [assets, query]);
  return <main className="mx-auto max-w-[1440px] space-y-5">
    <header className="flex flex-col gap-3 border-b border-slate-200 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-brand-600">IT Admin · Asset management</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight text-slate-950">All Assets</h1><p className="mt-1 text-sm text-slate-500">Manage and track all your organization assets in one place.</p></div><Link href="/assets/new" className="inline-flex items-center justify-center rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-brand-700">Add new asset</Link></header>
    <section className="grid overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm sm:grid-cols-3">{[["Total assets", String(assets.length), CubeIcon, "text-brand-600 bg-blue-50"], ["In use", String(assets.filter((asset) => asset.status === "In use").length), CheckCircleIcon, "text-emerald-600 bg-emerald-50"], ["Under maintenance", String(assets.filter((asset) => asset.status === "In repair").length), WrenchScrewdriverIcon, "text-amber-600 bg-amber-50"]].map(([label, value, Icon, style]) => <article key={label as string} className="flex items-center gap-4 border-b border-slate-200 px-5 py-5 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><span className={`grid h-11 w-11 place-items-center rounded-full ${style as string}`}><Icon className="h-5 w-5" /></span><div><p className="text-xs font-semibold text-slate-500">{label as string}</p><p className="mt-0.5 text-2xl font-extrabold text-slate-950">{value as string}</p></div></article>)}</section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-200 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-extrabold text-slate-950">Assets List</h2><p className="mt-0.5 text-xs text-slate-500">Showing {visibleAssets.length} of {assets.length} assets</p></div><input value={query} onChange={(event) => setQuery(event.target.value)} aria-label="Search assets" placeholder="Search by asset, user or status" className="w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm outline-none placeholder:text-slate-400 focus:border-brand-500 sm:w-72" /></div><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left"><thead className="bg-blue-50/70 text-[11px] font-bold text-slate-600"><tr>{["", "Asset ID", "Asset name", "Category", "Assigned to", "Status"].map((heading) => <th key={heading} className="px-5 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-200">{visibleAssets.map((asset) => { const Icon = categoryIcon[asset.category as keyof typeof categoryIcon] ?? CubeIcon; return <tr key={asset.id} className="text-sm hover:bg-slate-50"><td className="px-5 py-3 text-slate-500"><Icon className="h-4 w-4" /></td><td className="px-5 py-3 font-bold text-slate-700">#{asset.id}</td><td className="px-5 py-3 font-semibold text-slate-900">{asset.name}</td><td className="px-5 py-3 text-slate-600">{asset.category}</td><td className="px-5 py-3 text-slate-600">{asset.assignedTo}</td><td className="px-5 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${statusStyle[asset.status]}`}>{asset.status}</span></td></tr>; })}</tbody></table></div>{visibleAssets.length === 0 && <p className="p-10 text-center text-sm text-slate-500">No assets match your search.</p>}<footer className="border-t border-slate-200 px-5 py-4 text-sm text-slate-500">Showing 1 to {visibleAssets.length} of {assets.length} assets</footer></section>
    <section className="grid gap-4 md:grid-cols-2"><article className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-full bg-emerald-50 text-emerald-600"><ShieldCheckIcon className="h-6 w-6" /></span><div className="min-w-0 flex-1"><p className="text-sm font-bold text-slate-900">Warranty expiring soon</p><p className="mt-1 text-2xl font-extrabold">23</p><Link href="/assets" className="mt-1 inline-block text-xs font-bold text-brand-600 hover:text-brand-700">View assets</Link></div></article><article className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-full bg-fuchsia-50 text-fuchsia-600"><ClipboardDocumentCheckIcon className="h-6 w-6" /></span><div className="min-w-0 flex-1"><p className="text-sm font-bold text-slate-900">Assets due for audit</p><p className="mt-1 text-2xl font-extrabold">17</p><Link href="/reports" className="mt-1 inline-block text-xs font-bold text-brand-600 hover:text-brand-700">View assets</Link></div></article></section>
  </main>;
}
