"use client";

import { useState } from "react";

const scans = [
  { name: "Mumbai HQ network", range: "10.24.0.0/16", method: "SNMP · WMI · ICMP", devices: 842, status: "Complete", ran: "Today, 08:30" },
  { name: "Bengaluru office", range: "10.31.0.0/16", method: "SNMP · SSH · ICMP", devices: 616, status: "Complete", ran: "Today, 06:00" },
  { name: "London office", range: "10.47.0.0/16", method: "SNMP · WMI", devices: 294, status: "Running", ran: "Started 4 min ago" },
  { name: "Cloud agents", range: "Remote endpoints", method: "Agent telemetry", devices: 1_923, status: "Complete", ran: "Yesterday, 22:00" },
] as const;

const discoveries = [
  ["DESKTOP-4K8Q2", "Windows 11 Pro", "10.24.15.82", "Mumbai HQ", "3 min ago"],
  ["PRN-FIN-03", "HP LaserJet M607", "10.24.8.141", "Mumbai HQ", "17 min ago"],
  ["MAC-7D1J4", "macOS Sonoma 14.5", "10.31.3.109", "Bengaluru", "31 min ago"],
  ["SW-CORE-01", "Cisco Catalyst 9300", "10.47.0.12", "London", "1 hr ago"],
] as const;

export default function DiscoveryPage() {
  const [notice, setNotice] = useState(false);
  return <main className="mx-auto max-w-7xl space-y-8">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-brand-600">Automated asset discovery</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Discovery & scans</h1><p className="mt-2 text-slate-500">Find network-connected devices and collect endpoint telemetry.</p></div><button onClick={() => setNotice(true)} className="rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-700">+ Start discovery scan</button></header>
    {notice && <div role="status" className="flex items-center justify-between rounded-xl border border-brand-200 bg-brand-50 px-5 py-4 text-sm text-brand-900"><span>A new discovery scan has been queued. Connect it to the API to run it against a real network.</span><button onClick={() => setNotice(false)} className="ml-4 font-semibold">Dismiss</button></div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['3,675', 'Endpoints discovered', '+128 this month'], ['96.8%', 'Agent reporting rate', '3,558 active agents'], ['1', 'Scan in progress', 'London office network'], ['14', 'Unmanaged devices', 'Need owner assignment']].map(([value, label, hint], index) => <article key={label} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className={`text-2xl font-bold tracking-tight ${index === 3 ? "text-amber-600" : "text-slate-950"}`}>{value}</p><p className="mt-1 text-sm font-medium text-slate-700">{label}</p><p className="mt-2 text-xs text-slate-500">{hint}</p></article>)}</section>
    <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="font-semibold text-slate-900">Scheduled discovery jobs</h2><p className="mt-1 text-sm text-slate-500">Network ranges and telemetry sources monitored by Bold And Wise ITAM.</p></div><button className="text-sm font-semibold text-brand-600 hover:text-brand-700">Manage schedules →</button></div><div className="overflow-x-auto"><table className="min-w-[820px] w-full text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-3 font-semibold">Scan target</th><th className="px-6 py-3 font-semibold">Method</th><th className="px-6 py-3 font-semibold">Devices found</th><th className="px-6 py-3 font-semibold">Last run</th><th className="px-6 py-3 font-semibold">Status</th><th className="px-6 py-3" /></tr></thead><tbody className="divide-y divide-slate-100">{scans.map((scan) => <tr key={scan.name} className="hover:bg-slate-50"><td className="px-6 py-4"><p className="font-semibold text-slate-800">{scan.name}</p><p className="mt-0.5 text-sm text-slate-500">{scan.range}</p></td><td className="px-6 py-4 text-sm text-slate-600">{scan.method}</td><td className="px-6 py-4 text-sm font-semibold text-slate-700">{scan.devices.toLocaleString()}</td><td className="px-6 py-4 text-sm text-slate-600">{scan.ran}</td><td className="px-6 py-4"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${scan.status === "Running" ? "bg-blue-50 text-blue-700" : "bg-emerald-50 text-emerald-700"}`}>{scan.status}</span></td><td className="px-6 py-4 text-right"><button className="text-sm font-semibold text-brand-600 hover:text-brand-700">Details</button></td></tr>)}</tbody></table></div></section>
    <section className="grid gap-6 lg:grid-cols-[1.5fr_1fr]"><article className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="font-semibold text-slate-900">Recently discovered</h2><p className="mt-1 text-sm text-slate-500">New endpoints awaiting inventory reconciliation.</p></div><button className="text-sm font-semibold text-brand-600 hover:text-brand-700">View all →</button></div><div className="divide-y divide-slate-100">{discoveries.map(([name, platform, ip, location, time]) => <div key={name} className="flex items-center gap-4 px-6 py-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-brand-50 text-brand-600">●</span><div className="min-w-0 flex-1"><p className="font-semibold text-slate-800">{name}</p><p className="truncate text-sm text-slate-500">{platform} · {ip}</p></div><div className="hidden text-right text-sm text-slate-500 sm:block"><p>{location}</p><p className="mt-0.5 text-xs text-slate-400">{time}</p></div></div>)}</div></article><article className="rounded-xl bg-slate-950 p-6 text-white shadow-sm"><p className="text-sm font-medium text-slate-400">Discovery coverage</p><p className="mt-3 text-4xl font-bold">98.2%</p><p className="mt-2 text-sm leading-6 text-slate-400">Nearly all known network ranges have reported within the last 24 hours.</p><div className="mt-8 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[98.2%] rounded-full bg-brand-500" /></div><div className="mt-4 flex justify-between text-xs text-slate-400"><span>3,675 reporting</span><span>68 not seen</span></div><button className="mt-8 text-sm font-semibold text-brand-400 hover:text-brand-300">Review coverage gaps →</button></article></section>
  </main>;
}
