"use client";

import Link from "next/link";
import { useState } from "react";
import { CheckCircleIcon, ClipboardDocumentCheckIcon } from "@heroicons/react/24/outline";

type AssetOperationPageProps = { eyebrow: string; title: string; description: string; action: string; rows: readonly [string, string, string][] };

export function AssetOperationPage({ eyebrow, title, description, action, rows }: AssetOperationPageProps) {
  const [notice, setNotice] = useState("");
  return <main className="mx-auto max-w-7xl space-y-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-wider text-brand-600">{eyebrow}</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight text-slate-950">{title}</h1><p className="mt-1 text-sm text-slate-500">{description}</p></div><button type="button" onClick={() => setNotice(`${action} started. Connect this action to the ITAM API to persist it.`)} className="rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-brand-700">{action}</button></header>{notice && <div role="status" className="flex items-center justify-between rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800"><span>{notice}</span><button type="button" onClick={() => setNotice("")} aria-label="Dismiss notification">×</button></div>}<section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="text-base font-extrabold text-slate-900">Current items</h2><p className="mt-1 text-xs text-slate-500">Operational records for your organization.</p></div><ClipboardDocumentCheckIcon className="h-5 w-5 text-brand-500" /></div><div className="overflow-x-auto"><table className="min-w-[640px] w-full text-left"><thead className="bg-blue-50/70 text-[11px] font-bold text-slate-600"><tr><th className="px-5 py-3">Asset</th><th className="px-5 py-3">Owner / location</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(([asset, owner, status]) => <tr key={asset} className="text-sm hover:bg-slate-50"><td className="px-5 py-3 font-semibold text-slate-800">{asset}</td><td className="px-5 py-3 text-slate-600">{owner}</td><td className="px-5 py-3"><span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700"><CheckCircleIcon className="h-3.5 w-3.5" />{status}</span></td></tr>)}</tbody></table></div></section><Link href="/assets" className="inline-flex text-sm font-bold text-brand-600 hover:text-brand-700">← Back to all assets</Link></main>;
}
